version: '3.7'

services:
  nginx:
    container_name: nginx-transaction
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./public:/var/www/public
      - ./storage/app/public/:/var/www/public/storage/
    depends_on:
      - php
      - postgres

  php:
    container_name: php-transaction
    restart: always
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  postgres:
    container_name: postgres-transaction
    image: postgres:11
    user: "1000:50"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: transaction,transaction_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  composer:
    container_name: composer-transaction
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - postgres

  artisan:
    container_name: artisan-transaction
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    entrypoint: ['/var/www/artisan']
    depends_on:
      - postgres
    volumes:
      - ./:/var/www
